# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afea1bda23ce533777d84bf1fa057e674e7d418881a07b1faa6b0baa02064df8c410acbbdcc15370d5d201f06a7e35c4fbf0b010f99b80a5576c6a1e15602d30

test:
  secret_key_base: 31df630a143548b92fbd0f7086ba0f65a380170c2adb37b32f26144b5f53c3fda9b79a4448960709d11c3005b6adf3873bf7acaa8598e52a979c91b8e73c1c70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
